# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: youngmki <youngmki@student.42seoul.kr>     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/05/03 16:55:11 by youngmki          #+#    #+#              #
#    Updated: 2021/05/03 17:34:08 by youngmki         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

SRCS		=	ft_memset.c		\
				ft_b_zero.c		\

NAME		= 	libft.a

CC			=	gcc
CFLAG		=	-Wall -Wextra -Werror

INCLUDES	= ./libft.h

OBJS		= $(SRCS:.c=.o)
RM			= rm -f
		
